--Excluindo Tabelas
DROP TABLE PESSOAS;

--Criando Tabelas
CREATE TABLE PESSOAS(
    ID NUMBER(4) NOT NULL AUTO_INCREMENT,
    NOME VARCHAR2(50) NOT NULL,
    IDADE NUMBER(3),
    CONSTRAINT PK_PESSOAS PRIMARY KEY (ID)
);

--iNSERTS
INSERT INTO PESSOAS (NOME, IDADE) VALUES('Bruce Wayne', 35);
INSERT INTO PESSOAS (NOME, IDADE) VALUES('Bruce Banner', 41);
INSERT INTO PESSOAS (NOME, IDADE) VALUES('Tony Stark', 37);
INSERT INTO PESSOAS (NOME, IDADE) VALUES('Piter Parker', 19);
INSERT INTO PESSOAS (NOME, IDADE) VALUES('Clark Kent', 33);
INSERT INTO PESSOAS (NOME, IDADE) VALUES('Hank Pim', 47);