--Excluindo Tabelas
DROP TABLE PESSOAS;

--Criando Tabelas
CREATE TABLE PESSOAS(ID int(4) NOT NULL AUTO_INCREMENT,NOME VARCHAR(50) NOT NULL,IDADE int(3),CONSTRAINT PK_PESSOAS PRIMARY KEY (ID));

--iNSERTS
INSERT INTO PESSOAS (NOME, IDADE) VALUES('Bruce Wayne', 35);
INSERT INTO PESSOAS (NOME, IDADE) VALUES('Bruce Banner', 41);
INSERT INTO PESSOAS (NOME, IDADE) VALUES('Tony Stark', 37);
INSERT INTO PESSOAS (NOME, IDADE) VALUES('Piter Parker', 19);
INSERT INTO PESSOAS (NOME, IDADE) VALUES('Clark Kent', 33);
INSERT INTO PESSOAS (NOME, IDADE) VALUES('Hank Pim', 47);

CREATE TABLE CARROS(ID int(4) NOT NULL AUTO_INCREMENT,MODELO VARCHAR(50) NOT NULL,ANO int(4),CONSTRAINT PK_CARROS PRIMARY KEY (ID));

INSERT INTO CARROS (MODELO, ANO) VALUES('Gol', 2000);
INSERT INTO CARROS (MODELO, ANO) VALUES('Palio', 99);
INSERT INTO CARROS (MODELO, ANO) VALUES('Polo', 2008);
INSERT INTO CARROS (MODELO, ANO) VALUES('Uno', 96);
